Rails Associations Project: Private Events
alvarorf/rails-private-events pull request #1
Opened 2020-12-09 03:18 UTC by alvarorf

In this pull request, I attach the project Private Events for the Rails Curriculum. 
The purpose of this project was to implement associations in rails, in this case via the Private Events project. Therefore, users can create an account, login and logout, and only authorized users can create and attend (via an attendaces model/view/controller's combo) an event.
Thank you for your suggestions and any errors that you may find.

2020-12-09 05:59 UTC, elmejdki requested changes
# status: require changes :recycle: 

Great job @alvarorf I really liked your project :clap: :clap: :clap: :clap:, even though you still have some changes :hammer: :wrench: :toolbox: to make to get it approved :checkered_flag:.

Please check the comments below :point_down: :point_down: :point_down: :point_down: :point_down: 

- [ ] Your users show page is super confusing, it should only display events the user has created, and events that the user is attending to separated in past and upcoming.

- [ ] please fix the header on the top it's super hard to follow the header where it's gonna land to pick the next link to click in.

- [ ]  Please remove all the logic from your reviews and use view helpers to add logic into the code.

- [ ] Please add Unit tests, and integration tests to your project.

* [x] User model: `has_many :events, foreign_key: :creator_id` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

* [ ] Event model `belongs_to :creator, class_name: "User"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- [ ] In your schema for events table you have user_id and creator_id, please pick one I would recommend creator_id, and don't forget to add an index for it.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_If you have any questions or you feel stuck don't hesitate to contact me on slack I will be happy to help._

2020-12-09 05:59 UTC, elmejdki commented on app/controllers/events_controller.rb
> +    @past_events = @events.past
no need for the first line, you could do just:

```ruby

     @future_events = Event.upcoming
     @past_events = Event.past

```

2020-12-09 05:59 UTC, elmejdki commented on app/controllers/users_controller.rb
> +      @past_events = current_user.events.past
* [ ] lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming`

2020-12-09 05:59 UTC, elmejdki commented on app/views/devise/mailer/email_changed.html.erb
> +<% end %>
Please remove all the logic from your reviews and use view helpers to add logic into the code.

2020-12-09 05:59 UTC, elmejdki commented on app/views/devise/passwords/edit.html.erb
> +    <% end %>
Please remove all the logic from your reviews and use view helpers to add logic into the code.

2020-12-09 05:59 UTC, elmejdki commented on app/views/devise/registrations/new.html.erb
> +    <% end %><br />
Please remove all the logic from your reviews and use view helpers to add logic into the code.

2020-12-09 05:59 UTC, elmejdki commented on app/views/devise/shared/_links.html.erb
> +<% end %>
Please remove all the logic from your reviews and use view helpers to add logic into the code.

2020-12-23 18:44 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED 🛑 

Hello 👋 
A great effort implementing the changes requested by the previous TSE! 👍 
However, we still to make some changes in order to get the project approved 💪 
Kindly check my comments below 👇  implement the changes and request a new code review once done ⏩ 
Good luck! 😺 
## Mandatory changes
- Add unit tests to all the models, validations, associations and scopes
- Add integration tests to all the features of your app
- Remove test folder since you have your testing placed in spec folder
- Remove commented-out code in your controllers
- Remove json response since you are not using it in your controllers
- If you are not using actions, kindly remove it from your controller and routes
- In your schema for events table you have user_id and creator_id, please pick one I would recommend creator_id, and don't forget to add an index for it.
- And modify your models accordingly

2021-01-04 16:44 UTC, Temmarie requested changes
## Changes Required! :recycle:

### Hi @alvarorf  ! 👋 👋 

### You have done well so far :clap: However, there are changes required for you to make for this project to be approved. Kindly work on them and submit them for another code review.

**Recommended** 
- [ ] Add negative cases to your tests.
- [ ] Some of your tests are failing, kindly fix them.
**See here** 👇 
![Screenshot (173)](https://user-images.githubusercontent.com/49621279/103558082-6c1f4300-4eb4-11eb-9e20-9e678f75b1bf.png)


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-01-04 18:42 UTC, PhillipUg approved these changes
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this project approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

2021-01-04 21:34 UTC, merged